import {describe,expect,it,vi} from 'vitest';
import {syncIpPool,readbackIpPool,removeRemoteIpPool,assignPoolClient} from './ip-pools-sync.js';
vi.mock('./routers/secret-crypto.js',()=>({decryptRouterSecret:()=>JSON.stringify({username:'api-user',password:'long-password'})}));
const actor={id:7,status:'Active',role:'Reseller'};
function database(){const query=vi.fn(async(sql,args)=>{if(sql.includes('from app_ip_pools p join app_routers'))return {rows:[{id:3,name:'Subscribers',network:'10.20.0.0/24',routerId:9,remoteName:null,host:'router.example',port:8729,routerOsVersion:'6',encryptedValue:'v1:x'}]};if(sql.includes('update app_ip_pools set remote_name'))return {rows:[{id:3,name:'Subscribers',network:'10.20.0.0/24',routerId:9,remoteName:'Subscribers',syncStatus:'Synced'}]};if(sql.includes('update app_clients'))return {rows:[{id:22}]};return {rows:[]}});return {query}}
describe('IP pool synchronization',()=>{
 it('provisions and verifies exact readback for RouterOS 6/7 adapter contract',async()=>{const db=database(),adapter={listPools:vi.fn().mockResolvedValueOnce([]).mockResolvedValueOnce([{'.id':'*1',name:'Subscribers',ranges:'10.20.0.1-10.20.0.254'}]),addPool:vi.fn(),setPool:vi.fn()};const result=await syncIpPool(db,actor,3,'a'.repeat(64),{adapter});expect(adapter.addPool).toHaveBeenCalledWith('Subscribers','10.20.0.1-10.20.0.254');expect(result.syncStatus).toBe('Synced')});
 it('marks mismatched readback as drifted',async()=>{const db=database(),adapter={listPools:vi.fn().mockResolvedValue([{'.id':'*1',name:'Subscribers',ranges:'10.20.0.1-10.20.0.200'}])};const result=await readbackIpPool(db,actor,3,'a'.repeat(64),{adapter});expect(result.matched).toBe(false);expect(db.query).toHaveBeenCalledWith(expect.stringContaining('sync_status=$3'),[3,7,'Drifted'])});
 it('assigns only an owned active pool/client pair',async()=>{const db=database();await expect(assignPoolClient(db,actor,3,22)).resolves.toEqual({poolId:3,clientId:22,assigned:true});expect(db.query).toHaveBeenCalledWith(expect.stringContaining('c.owner_user_id=$3'),[3,22,7])});
 it('removes a remote pool and verifies cleanup',async()=>{const db=database();db.connect=vi.fn().mockResolvedValue({query:db.query,release:vi.fn()});const adapter={listPools:vi.fn().mockResolvedValueOnce([{'.id':'*1',name:'Subscribers',ranges:'10.20.0.1-10.20.0.254'}]).mockResolvedValueOnce([]),removePool:vi.fn(),addPool:vi.fn()};await expect(removeRemoteIpPool(db,actor,3,'a'.repeat(64),{adapter})).resolves.toEqual({poolId:3,removed:true});expect(adapter.removePool).toHaveBeenCalledWith('*1')});
 it('denies impersonated financial-style writes',async()=>{await expect(assignPoolClient(database(),{...actor,impersonatedBy:{id:1}},3,22)).rejects.toMatchObject({status:403})});
});
