import {isIP} from 'node:net';
const invalid=message=>Object.assign(new Error(message),{status:422});
const conflict=message=>Object.assign(new Error(message),{status:409});
const missing=()=>Object.assign(new Error('IP pool not found'),{status:404});
const owner=actor=>{if(!actor||actor.status!=='Active'||actor.impersonatedBy||!Number.isSafeInteger(Number(actor.id))||Number(actor.id)<=0)throw Object.assign(new Error('Active own-tenant session required'),{status:403});return Number(actor.id)};
const positive=(value,label)=>{const id=Number(value);if(!/^[1-9][0-9]*$/.test(String(value))||!Number.isSafeInteger(id))throw invalid(`Invalid ${label}`);return id};
export function parseIpPool(body){
 const name=String(body?.name??'').trim(),network=String(body?.network??'').trim(),status=body?.status??'Active';
 const routerId=body?.routerId===''||body?.routerId==null?null:positive(body.routerId,'router ID');
 if(name.length<2||name.length>80||!['Active','Disabled'].includes(status))throw invalid('Invalid IP pool fields');
 const parts=network.split('/');if(parts.length!==2||isIP(parts[0])!==4||!/^[0-9]{1,2}$/.test(parts[1])||Number(parts[1])<8||Number(parts[1])>30)throw invalid('IPv4 network CIDR (/8 to /30) required');
 const raw=parts[0].split('.'),octets=raw.map(Number),prefix=Number(parts[1]);if(octets.some((n,i)=>String(n)!==raw[i]))throw invalid('Canonical IPv4 network required');
 const address=octets.reduce((n,x)=>((n<<8)|x)>>>0,0),mask=(0xffffffff<<(32-prefix))>>>0;if((address&mask)!==address)throw invalid('CIDR must start at the network address');
 return {name,network,status,routerId};
}
const fields=`p.id,p.name,p.network::text network,p.status,p.router_id "routerId",p.remote_name "remoteName",p.sync_status "syncStatus",p.last_synced_at "lastSyncedAt",r.name "routerName",r.router_os_version "routerOsVersion",(select count(*)::int from app_clients c where c.owner_user_id=p.owner_user_id and c.ip_pool_id=p.id) "clientCount",p.created_at "createdAt",p.updated_at "updatedAt"`;
export async function listIpPools(db,actor){const result=await db.query(`select ${fields} from app_ip_pools p left join app_routers r on r.id=p.router_id and r.owner_user_id=p.owner_user_id where p.owner_user_id=$1 order by p.name,p.id`,[owner(actor)]);return result.rows}
export async function saveIpPool(pool,actor,body,idValue){const userId=owner(actor),value=parseIpPool(body),id=idValue===undefined?null:positive(idValue,'IP pool ID'),db=await pool.connect();try{await db.query('BEGIN');await db.query('select pg_advisory_xact_lock(778115,$1)',[userId]);if(value.routerId!==null){const r=await db.query('select id from app_routers where id=$1 and owner_user_id=$2 and deleted_at is null',[value.routerId,userId]);if(!r.rows[0])throw invalid('Selected router is unavailable')}if(id!==null){const exists=await db.query('select id,remote_name from app_ip_pools where id=$1 and owner_user_id=$2 for update',[id,userId]);if(!exists.rows[0])throw missing();if(exists.rows[0].remote_name&&(value.routerId===null))throw conflict('Remove the pool from RouterOS before clearing its router')}
 const overlapping=await db.query('select id from app_ip_pools where owner_user_id=$1 and network && $2::cidr and ($3::bigint is null or id<>$3) limit 1',[userId,value.network,id]);if(overlapping.rows[0])throw conflict('IP pool overlaps an existing tenant pool');
 const result=id===null?await db.query(`insert into app_ip_pools(owner_user_id,name,network,status,router_id) values($1,$2,$3,$4,$5) returning id`,[userId,value.name,value.network,value.status,value.routerId]):await db.query(`update app_ip_pools set name=$3,network=$4,status=$5,router_id=$6,sync_status=case when remote_name is null then 'Local' else 'Drifted' end,updated_at=now() where id=$1 and owner_user_id=$2 returning id`,[id,userId,value.name,value.network,value.status,value.routerId]);
 await db.query('COMMIT');return (await listIpPools(pool,actor)).find(p=>p.id===result.rows[0].id)}catch(error){await db.query('ROLLBACK').catch(()=>{});if(error.code==='23505')throw conflict('IP pool name, network or remote mapping already exists');if(error.code==='22P02')throw invalid('Invalid IPv4 CIDR');throw error}finally{db.release()}}
export async function deleteIpPool(pool,actor,idValue){const userId=owner(actor),id=positive(idValue,'IP pool ID'),db=await pool.connect();try{await db.query('BEGIN');const {rows}=await db.query(`select p.id,p.remote_name "remoteName",(select count(*)::int from app_clients c where c.owner_user_id=p.owner_user_id and c.ip_pool_id=p.id) clients from app_ip_pools p where p.id=$1 and p.owner_user_id=$2 for update`,[id,userId]);if(!rows[0])throw missing();if(rows[0].remoteName)throw conflict('Remove the synchronized RouterOS pool first');if(rows[0].clients)throw conflict('IP pool is assigned to clients');await db.query('delete from app_ip_pools where id=$1 and owner_user_id=$2',[id,userId]);await db.query('COMMIT')}catch(e){await db.query('ROLLBACK').catch(()=>{});throw e}finally{db.release()}}
