import React,{useMemo,useState} from'react';import{createRoot}from'react-dom/client';
import{Activity,Bell,ChevronDown,CreditCard,FileText,Gauge,Headphones,LayoutDashboard,Menu,Network,Package,Plus,RadioTower,ReceiptText,Search,Server,Settings,ShieldCheck,Signal,Users,UserRoundCog,WalletCards,Wifi,X,Zap}from'lucide-react';
import{Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';import'./styles.css';
const traffic=[{t:'12 AM',down:65},{t:'4 AM',down:48},{t:'8 AM',down:110},{t:'12 PM',down:162},{t:'4 PM',down:205},{t:'8 PM',down:236},{t:'Now',down:198}];
const clients=[
{name:'Saifan Net 1021',user:'saifan-net-1021',phone:'01700-000001',package:'20 Mbps',router:'Dhaka-Core-01',ip:'10.22.4.18',expiry:'17 Oct 2026',bill:'৳800',status:'Online'},
{name:'Rahim Home',user:'rahim-home-77',phone:'01800-000077',package:'10 Mbps',router:'Gazipur-NAS-02',ip:'10.23.8.201',expiry:'12 Oct 2026',bill:'৳500',status:'Offline'},
{name:'Hasan Office',user:'hasan-office-12',phone:'01900-000012',package:'30 Mbps',router:'Narayanganj-01',ip:'10.24.1.94',expiry:'28 Sep 2026',bill:'৳1,200',status:'Online'},
{name:'Mim Enterprise',user:'mim-enterprise',phone:'01600-000009',package:'50 Mbps',router:'Dhaka-Core-01',ip:'10.22.9.11',expiry:'15 Sep 2026',bill:'৳2,000',status:'Expired'},
{name:'Jahid Telecom',user:'jahid-tel-08',phone:'01300-000008',package:'20 Mbps',router:'Comilla-NAS-01',ip:'10.25.7.32',expiry:'03 Oct 2026',bill:'৳800',status:'Offline'}];
const nav=[['Workspace',[['Dashboard',LayoutDashboard],['Clients',Users],['Live Sessions',Activity]]],['Services',[['Packages',Package],['IP Pools',Network],['Routers / NAS',Server],['RADIUS Monitor',RadioTower]]],['Business',[['Resellers',UserRoundCog],['Wallet & Ledger',WalletCards],['Billing',ReceiptText],['Reports',FileText]]],['Account',[['My Profile',ShieldCheck],['Settings',Settings]]]];
const roles={Admin:{title:'ISP Administrator',org:'NextGan Networks',counts:[['Total Clients','12,840',Users,'violet'],['Online','8,426',Signal,'cyan'],['Offline','3,546',Wifi,'orange'],['Expired','868',CreditCard,'red']]},Reseller:{title:'Reseller Dashboard',org:'Saifan Distribution',counts:[['Total Clients','486',Users,'violet'],['Online','328',Signal,'cyan'],['Offline','124',Wifi,'orange'],['Expired','34',CreditCard,'red']]},'Sub-reseller':{title:'Sub-reseller Dashboard',org:'Gazipur Zone',counts:[['Total Clients','128',Users,'violet'],['Online','84',Signal,'cyan'],['Offline','35',Wifi,'orange'],['Expired','9',CreditCard,'red']]}};
function Stat({x}){const[L,V,I,T]=x;return <article className={`stat ${T}`}><div className="stat-top"><span className="stat-icon"><I/></span></div><strong>{V}</strong><p>{L}</p></article>}
function Table({rows,compact}){return <div className="table-wrap"><table><thead><tr><th>Client</th><th>Username</th><th>Package</th>{!compact&&<th>Router / IP</th>}<th>Expiry</th>{!compact&&<th>Bill</th>}<th>Status</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.user}><td><b>{c.name}</b>{!compact&&<small className="cell-sub">{c.phone}</small>}</td><td>{c.user}</td><td><span className="plan-pill">{c.package}</span></td>{!compact&&<td>{c.router}<small className="cell-sub">{c.ip}</small></td>}<td>{c.expiry}</td>{!compact&&<td>{c.bill}</td>}<td><span className={`status ${c.status.toLowerCase()}`}><i/>{c.status}</span></td><td><button className="row-action">•••</button></td></tr>)}</tbody></table></div>}
function Dashboard({role}){let c=roles[role];return <div className="content"><section className="welcome"><div><p>THURSDAY, 17 SEPTEMBER</p><h1>{c.title}</h1><span>Everything important, in one clean view</span></div><div className="period"><button className="selected">Today</button><button>7 days</button><button>30 days</button></div></section><section className="stats">{c.counts.map(x=><Stat x={x} key={x[0]}/>)}</section><section className="minimal-grid"><article className="panel"><div className="panel-head"><div><h2>Live Bandwidth</h2><p>All active sessions</p></div><div className="throughput"><b>198.4</b><span>↓ Mbps</span><b>78.2</b><span>↑ Mbps</span></div></div><div className="chart compact"><ResponsiveContainer><AreaChart data={traffic}><defs><linearGradient id="tf" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5b5cf0" stopOpacity={.35}/><stop offset="1" stopColor="#5b5cf0" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 6" vertical={false}/><XAxis dataKey="t" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="down" stroke="#5b5cf0" strokeWidth={3} fill="url(#tf)"/></AreaChart></ResponsiveContainer></div></article><article className="panel quick-panel"><div className="panel-head"><div><h2>{role==='Admin'?'System Status':'Wallet Summary'}</h2><p>Live operational health</p></div><span className="health-badge"><i/>Healthy</span></div>{role==='Admin'?<div className="mini-list"><div><span><Server/>Routers / NAS</span><b>24 / 25</b></div><div><span><RadioTower/>RADIUS nodes</span><b>2 / 2</b></div><div><span><Gauge/>Auth latency</span><b>18 ms</b></div><div><span><ShieldCheck/>Auth success</span><b>99.4%</b></div></div>:<div className="wallet-summary"><small>Available wallet</small><strong>৳84,650</strong><span>৳12,800 recharged today</span><button>Open wallet & ledger</button></div>}</article></section><section className="panel concise-table"><div className="panel-head"><div><h2>Recent Clients</h2><p>Latest subscriber activity</p></div><button>View all clients</button></div><Table rows={clients.slice(0,4)} compact/></section></div>}
function Clients(){let[q,setQ]=useState(''),[f,setF]=useState('All');let rows=useMemo(()=>clients.filter(c=>(f==='All'||c.status===f)&&`${c.name} ${c.user} ${c.phone}`.toLowerCase().includes(q.toLowerCase())),[q,f]);return <div className="content"><section className="page-title"><div><h1>Clients</h1><p>Accounts, packages, billing and sessions</p></div><button className="quick"><Plus/>Add Client</button></section><section className="panel client-panel"><div className="client-tools"><div className="search inner"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, username or mobile"/></div><div className="filters">{['All','Online','Offline','Expired'].map(x=><button className={f===x?'selected':''} onClick={()=>setF(x)} key={x}>{x}</button>)}</div></div><Table rows={rows}/>{!rows.length&&<div className="empty">No clients matched this filter.</div>}</section></div>}
function Simple({name}){return <div className="content"><section className="page-title"><div><h1>{name}</h1><p>Focused workspace for {name.toLowerCase()}.</p></div></section><section className="panel module-placeholder"><div className="placeholder-icon"><Zap/></div><h2>{name} workspace</h2><p>Responsive layout is ready. Forms, validation and API operations follow in the next checkpoint.</p></section></div>}
function App(){let[open,setOpen]=useState(false),[active,setActive]=useState('Dashboard'),[role,setRole]=useState('Admin');let page=active==='Dashboard'?<Dashboard role={role}/>:active==='Clients'?<Clients/>:<Simple name={active}/>;return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark"><RadioTower/></div><div><b>PPPoE</b><span>RADIUS INTEGRATION</span></div><button className="side-close" onClick={()=>setOpen(false)}><X/></button></div><div className="tenant"><div className="tenant-icon">NG</div><div><small>{role} view</small><strong>{roles[role].org}</strong></div><ChevronDown/></div><nav>{nav.map(([g,is])=><div className="nav-group" key={g}><p>{g}</p>{is.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>{setActive(n);setOpen(false)}}><I/><span>{n}</span></button>)}</div>)}</nav><div className="support"><Headphones/><div><b>Need assistance?</b><span>24/7 Network Support</span></div></div><div className="profile"><div className="avatar">SI</div><div><b>Saifan Islam</b><span>{roles[role].title}</span></div><button><Settings/></button></div></aside>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="search"><Search/><input placeholder="Search clients, routers, invoices..."/></div><div className="head-actions"><select className="role-select" value={role} onChange={e=>{setRole(e.target.value);setActive('Dashboard')}}><option>Admin</option><option>Reseller</option><option>Sub-reseller</option></select><div className="live"><i/>RADIUS Live</div><button className="icon-btn"><Bell/><span>3</span></button><button className="quick"><Zap/>Quick Recharge</button></div></header>{page}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
